# Generated by Django 5.1.7 on 2025-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique_app', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
